# Copyright 2025 Observational Health Data Sciences and Informatics
#
# This file is part of CohortMethod
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Test the proportional hazards assumption for a Cox model
#'
#' @description
#' Test the proportional hazards assumption using the Grambsch-Therneau test based on
#' Schoenfeld residuals.
#'
#' @details
#' This function tests whether the proportional hazards assumption holds for a fitted Cox
#' model. The test is based on the correlation between Schoenfeld residuals and time
#' (Grambsch-Therneau test). A significant p-value indicates violation of the proportional
#' hazards assumption.
#'
#' **Model Reuse**: If an `OutcomeModel` object is provided and contains a fitted coxph model
#' (outcomeModel$coxphFit), this fitted model is used directly for PH testing. When the
#' original outcome model was fitted with covariates (useCovariates = TRUE), the stored
#' coxphFit includes all covariates that had non-zero coefficients in the Cyclops model,
#' enabling full covariate-adjusted PH testing.
#' If no fitted model is available, a simple Cox model is fitted internally.
#'
#' **Study Design Handling**:
#' - **Stratified designs**: The test accounts for stratification via strata(stratumId)
#' - **Matched designs**: Cluster-robust variance is used via cluster(matchId) to account
#'   for within-pair correlation
#' - **IPTW**: Robust variance estimation is used (if robustVariance = TRUE), and extreme
#'   weights are truncated according to iptwTruncation limits
#'
#' @param population            A population object generated by [createStudyPopulation()],
#'                              potentially filtered by other functions. Must include columns:
#'                              rowId, treatment, survivalTime, outcomeCount. Optional columns:
#'                              stratumId (for stratified models), matchId (for matched designs),
#'                              iptw (for weighted models).
#' @param outcomeModel          An optional `OutcomeModel` object from [fitOutcomeModel()].
#'                              If provided and contains a fitted coxph model (outcomeModel$coxphFit),
#'                              this fitted model will be used directly, including all covariates
#'                              from the original Cyclops model. If NULL, a simple Cox model
#'                              will be fitted.
#' @param pValueThreshold       The p-value threshold for flagging PH violations. Default is 0.05.
#' @param transform             Time transformation for the test. Options are "km" (Kaplan-Meier,
#'                              recommended), "rank", or "identity". Default is "km".
#' @param includeGlobalTest     Whether to include a global test across all covariates.
#'                              Default is TRUE.
#' @param iptwTruncation        A numeric vector of length 2 specifying the lower and upper
#'                              truncation limits for IPTW weights. Default is c(0.1, 10).
#'                              Only applied when population contains iptw column.
#' @param robustVariance        Whether to use robust variance estimation for IPTW models.
#'                              Default is TRUE. For matched designs, cluster-robust variance
#'                              is automatically used via cluster(matchId).
#'
#' @return
#' An object of class `PhTestResult` containing:
#' \describe{
#'   \item{global}{A data frame with global test statistics (if includeGlobalTest = TRUE)}
#'   \item{covariates}{A data frame with test results for each covariate}
#'   \item{settings}{A list with test settings and metadata}
#'   \item{schoenfeld}{A list with Schoenfeld residuals for diagnostic plotting}
#' }
#'
#' @examples
#' \dontrun{
#' # After creating a study population and fitting a Cox model:
#' population <- createStudyPopulation(
#'   cohortMethodData = cohortMethodData,
#'   outcomeId = 3,
#'   removeSubjectsWithPriorOutcome = TRUE
#' )
#'
#' outcomeModel <- fitOutcomeModel(
#'   population = population,
#'   modelType = "cox"
#' )
#'
#' # Test proportional hazards assumption
#' phTest <- testProportionalHazards(
#'   population = population,
#'   outcomeModel = outcomeModel
#' )
#'
#' print(phTest)
#'
#' # If p-value < 0.05, consider using RMST instead of hazard ratios
#' }
#'
#' @references
#' Grambsch, P. M., & Therneau, T. M. (1994). Proportional hazards tests and diagnostics
#' based on weighted residuals. Biometrika, 81(3), 515-526.
#'
#' @export
testProportionalHazards <- function(population,
                                    outcomeModel = NULL,
                                    pValueThreshold = 0.05,
                                    transform = "km",
                                    includeGlobalTest = TRUE,
                                    iptwTruncation = c(0.1, 10),
                                    robustVariance = TRUE) {
  errorMessages <- checkmate::makeAssertCollection()
  checkmate::assertDataFrame(population, add = errorMessages)
  checkmate::assertClass(outcomeModel, "OutcomeModel", null.ok = TRUE, add = errorMessages)
  checkmate::assertNumber(pValueThreshold, lower = 0, upper = 1, add = errorMessages)
  checkmate::assertNumeric(iptwTruncation, len = 2, add = errorMessages)
  checkmate::assertLogical(robustVariance, len = 1, add = errorMessages)
  checkmate::assertChoice(transform, c("km", "rank", "identity"), add = errorMessages)
  checkmate::assertLogical(includeGlobalTest, len = 1, add = errorMessages)
  checkmate::reportAssertions(collection = errorMessages)

  .validatePopulation(population, minEvents = 10, minSubjects = 50)

  warnings <- character()
  usedFittedModel <- FALSE

  if (!is.null(outcomeModel) && !is.null(outcomeModel$coxphFit)) {
    coxFit <- outcomeModel$coxphFit
    usedFittedModel <- TRUE

    if (isTRUE(outcomeModel$coxphFitSimplified)) {
      warning(paste(
        "The stored coxphFit is simplified: covariates from the original Cyclops model",
        "could not be reconstructed. The PH test is performed on treatment effect only.",
        "Results may differ from testing the full covariate-adjusted model."
      ))
    } else {
      nIncluded <- outcomeModel$coxphFitNCovariatesIncluded %||% 0
      if (nIncluded > 0) {
        ParallelLogger::logInfo(
          "Using coxph model with ", nIncluded, " covariates for PH testing"
        )
      }
    }

    ParallelLogger::logInfo("Using fitted Cox model from OutcomeModel for PH testing")

    isStratified <- !is.null(coxFit$strata)
    hasWeights <- !is.null(coxFit$weights)
    nSubjects <- coxFit$n
    nEvents <- coxFit$nevent
  } else {
    if (!is.null(outcomeModel)) {
      ParallelLogger::logWarn("OutcomeModel provided but no coxphFit found - rebuilding simplified Cox model")
    }

    data <- .extractSurvivalData(population, outcomeModel)

    isStratified <- !is.null(data$stratumId)
    hasWeights <- !is.null(data$iptw)
    isMatched <- !is.null(data$matchId)

    if (hasWeights && isMatched) {
      stop("Multiple adjustment methods detected: matching (matchId) and IPTW (iptw). Population should contain only one adjustment method.")
    }

    if (hasWeights) {
      data$iptw <- .handleExtremeWeights(data$iptw)
    }

    if (isStratified) {
      eventsByStratum <- aggregate(data$event,
        by = list(stratum = data$stratumId),
        FUN = sum
      )
      minEvents <- min(eventsByStratum$x)
      if (minEvents < 5) {
        warning(sprintf(
          "Some strata have fewer than 5 events (minimum: %d). PH testing may be unreliable.",
          minEvents
        ))
      }
    }

    if (isStratified) {
      formula <- survival::Surv(time, event) ~ treatment + strata(stratumId)
    } else if (isMatched) {
      formula <- survival::Surv(time, event) ~ treatment + cluster(matchId)
    } else {
      formula <- survival::Surv(time, event) ~ treatment
    }

    if (hasWeights && !is.null(iptwTruncation)) {
      lowerLimit <- iptwTruncation[1]
      upperLimit <- iptwTruncation[2]
      data$iptw <- pmax(lowerLimit, pmin(data$iptw, upperLimit))
      ParallelLogger::logTrace(sprintf("Applied IPTW truncation: [%.2f, %.2f]", lowerLimit, upperLimit))
    }

    if (hasWeights) {
      if (robustVariance) {
        coxFit <- tryCatch(
          {
            survival::coxph(formula, data = data.frame(data), weights = data$iptw, robust = TRUE)
          },
          error = function(e) {
            warning("Robust variance estimation failed: ", e$message, ". Falling back to standard variance.")
            survival::coxph(formula, data = data.frame(data), weights = data$iptw)
          }
        )
      } else {
        coxFit <- tryCatch(
          {
            survival::coxph(formula, data = data.frame(data), weights = data$iptw)
          },
          error = function(e) {
            stop("Failed to fit Cox model: ", e$message)
          }
        )
      }
    } else if (isMatched) {
      coxFit <- tryCatch(
        {
          survival::coxph(formula, data = data.frame(data))
        },
        error = function(e) {
          stop("Failed to fit Cox model with cluster variance: ", e$message)
        }
      )
    } else {
      coxFit <- tryCatch(
        {
          survival::coxph(formula, data = data.frame(data))
        },
        error = function(e) {
          stop("Failed to fit Cox model: ", e$message)
        }
      )
    }

    nSubjects <- length(unique(data$rowId))
    nEvents <- sum(data$event)
  }

  ParallelLogger::logInfo(sprintf(
    "Performing proportional hazards test (transform='%s', N=%d, events=%d)",
    transform, nSubjects, nEvents
  ))

  phTest <- tryCatch(
    {
      survival::cox.zph(coxFit, transform = transform)
    },
    error = function(e) {
      stop("Failed to perform proportional hazards test: ", e$message)
    }
  )

  testTable <- as.data.frame(phTest$table)

  treatmentRowName <- "treatment"
  if (!treatmentRowName %in% rownames(testTable)) {
    stop("Treatment coefficient not found in PH test results. Model may have convergence issues.")
  }

  covariateResults <- data.frame(
    covariateId = 1,
    covariateName = "Treatment",
    testStatistic = testTable[treatmentRowName, "chisq"],
    df = 1,
    pValue = testTable[treatmentRowName, "p"],
    violated = testTable[treatmentRowName, "p"] < pValueThreshold,
    stringsAsFactors = FALSE
  )

  globalTest <- NULL
  if (includeGlobalTest && nrow(testTable) > 1) {
    globalTest <- data.frame(
      testStatistic = testTable["GLOBAL", "chisq"],
      df = as.integer(testTable["GLOBAL", "df"]),
      pValue = testTable["GLOBAL", "p"]
    )
  }

  schoenfeldResiduals <- list(
    time = phTest$time,
    residuals = phTest$y
  )

  if (any(covariateResults$violated)) {
    violatedCovs <- covariateResults$covariateName[covariateResults$violated]
    msg <- sprintf(
      "Proportional hazards assumption violated (p < %.2f) for: %s",
      pValueThreshold, paste(violatedCovs, collapse = ", ")
    )
    warning(msg)
    warnings <- c(warnings, msg)
  }

  result <- list(
    global = globalTest,
    covariates = covariateResults,
    settings = list(
      pValueThreshold = pValueThreshold,
      transform = transform,
      nSubjects = nSubjects,
      nEvents = nEvents,
      stratified = isStratified,
      weighted = hasWeights,
      usedFittedModel = usedFittedModel,
      warnings = if (length(warnings) > 0) warnings else NULL
    ),
    schoenfeld = schoenfeldResiduals
  )

  class(result) <- "PhTestResult"
  return(result)
}

#' Print method for PhTestResult
#'
#' @param x An object of class `PhTestResult`.
#' @param ... Additional arguments (not used).
#'
#' @export
print.PhTestResult <- function(x, ...) {
  cat("Proportional Hazards Test Results\n")
  cat("=====================================\n\n")

  cat(sprintf(
    "Sample size: %d subjects, %d events\n",
    x$settings$nSubjects, x$settings$nEvents
  ))
  cat(sprintf(
    "Stratified: %s, Weighted: %s\n\n",
    x$settings$stratified, x$settings$weighted
  ))

  if (!is.null(x$global)) {
    cat("Global Test:\n")
    cat(sprintf(
      "  Chi-square = %.2f (df = %d), p-value = %.4f\n\n",
      x$global$testStatistic, x$global$df, x$global$pValue
    ))
  }

  cat("Covariate Tests:\n")
  for (i in seq_len(nrow(x$covariates))) {
    row <- x$covariates[i, ]
    violation <- if (row$violated) " *VIOLATION*" else ""
    cat(sprintf(
      "  %s: Chi-square = %.2f (df = %d), p-value = %.4f%s\n",
      row$covariateName, row$testStatistic, row$df, row$pValue, violation
    ))
  }

  if (any(x$covariates$violated)) {
    cat("\n* p-value < ", x$settings$pValueThreshold, " indicates PH assumption violation\n", sep = "")
  }

  invisible(x)
}

.extractSurvivalData <- function(population, outcomeModel = NULL) {
  errorMessages <- checkmate::makeAssertCollection()
  checkmate::assertDataFrame(population, add = errorMessages)
  checkmate::assertNames(names(population),
    must.include = c("rowId", "treatment", "survivalTime", "outcomeCount"),
    add = errorMessages
  )
  checkmate::reportAssertions(collection = errorMessages)

  data <- list(
    rowId = population$rowId,
    time = population$survivalTime,
    event = population$outcomeCount,
    treatment = population$treatment
  )

  if ("stratumId" %in% names(population)) {
    data$stratumId <- population$stratumId
  } else {
    data$stratumId <- NULL
  }

  if ("matchId" %in% names(population)) {
    data$matchId <- population$matchId
  } else {
    data$matchId <- NULL
  }

  if ("iptw" %in% names(population)) {
    data$iptw <- population$iptw
  } else {
    data$iptw <- NULL
  }

  return(data)
}

.validatePopulation <- function(population, minEvents = 10, minSubjects = 50) {
  errorMessages <- checkmate::makeAssertCollection()
  checkmate::assertDataFrame(population, min.rows = minSubjects, add = errorMessages)
  checkmate::assertNames(names(population),
    must.include = c("rowId", "treatment", "survivalTime", "outcomeCount"),
    add = errorMessages
  )
  checkmate::reportAssertions(collection = errorMessages)

  if (any(is.na(population$survivalTime))) {
    stop("Missing values detected in survivalTime")
  }
  if (any(is.na(population$outcomeCount))) {
    stop("Missing values detected in outcomeCount")
  }
  if (any(is.na(population$treatment))) {
    stop("Missing values detected in treatment")
  }

  nEvents <- sum(population$outcomeCount)
  if (nEvents < minEvents) {
    stop(sprintf(
      "Insufficient events: %d events found, minimum %d required",
      nEvents, minEvents
    ))
  }

  if (any(population$survivalTime <= 0)) {
    stop("survivalTime must be positive")
  }

  if (!all(population$outcomeCount %in% c(0, 1))) {
    stop("outcomeCount must be binary (0 or 1)")
  }

  if (!all(population$treatment %in% c(0, 1))) {
    stop("treatment must be binary (0 or 1)")
  }

  return(TRUE)
}
